spring:
  data:
    mongodb:
#      host: host
#      port: port
      database: otushomework
      uri: mongodb://admin:Bac12345@cluster0-shard-00-00-lncxp.mongodb.net:27017,cluster0-shard-00-01-lncxp.mongodb.net:27017,cluster0-shard-00-02-lncxp.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:acl_db
      username: sa
      password:
      schema: classpath:schema.sql